import { Button, VerticalBox, CheckBox, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> interval: 42;
    callback request-chkbox-value();
    // width: 300px;
    // height: 250px;

    VerticalBox {
        Text { 
            text: "Water Break Configurator"; 
            // width: parent.width;
            height: 30px;
            vertical-alignment: top;
            horizontal-alignment: center;
        }
        Text {
            text: "Set reminder interval for breaks in minutes.";
            height: 20px;
        }
        
        Slider {
            min-width: 20px;
            max-width: 50px;
            value: 10;
            padding-left: 10px;
            padding-right: 10px;
            maximum: 70;
            changed => {
                root.interval = self.value;
            }
        }

        Text {
            text: "Reminding every: \{root.interval}";
            height: 20px;
        }

        CheckBox {
            text: "Enabled";
            checked: false;
            toggled => {
                root.request-chkbox-value();
            }
        }
        
    }
}
